// Index constituents — update quarterly when indices rebalance.
// Intentionally a separate file so it can be updated without touching logic.
import { AssetBucket } from './config';

export interface Constituent {
  symbol: string;
  name: string;
  bucket: AssetBucket;
}

export const DAX40: readonly Constituent[] = [
  { symbol: 'ADS.DE',  name: 'adidas',             bucket: 'eu' },
  { symbol: 'AIR.DE',  name: 'Airbus',              bucket: 'eu' },
  { symbol: 'ALV.DE',  name: 'Allianz',             bucket: 'eu' },
  { symbol: 'BAS.DE',  name: 'BASF',                bucket: 'eu' },
  { symbol: 'BAYN.DE', name: 'Bayer',               bucket: 'eu' },
  { symbol: 'BEI.DE',  name: 'Beiersdorf',          bucket: 'eu' },
  { symbol: 'BMW.DE',  name: 'BMW',                 bucket: 'eu' },
  { symbol: 'BNR.DE',  name: 'Brenntag',            bucket: 'eu' },
  { symbol: 'CON.DE',  name: 'Continental',         bucket: 'eu' },
  { symbol: 'DB1.DE',  name: 'Deutsche Börse',      bucket: 'eu' },
  { symbol: 'DBK.DE',  name: 'Deutsche Bank',       bucket: 'eu' },
  { symbol: 'DHL.DE',  name: 'DHL Group',           bucket: 'eu' },
  { symbol: 'DTE.DE',  name: 'Deutsche Telekom',    bucket: 'eu' },
  { symbol: 'DTG.DE',  name: 'Daimler Truck',       bucket: 'eu' },
  { symbol: 'ENR.DE',  name: 'Siemens Energy',      bucket: 'eu' },
  { symbol: 'EOAN.DE', name: 'E.ON',                bucket: 'eu' },
  { symbol: 'FME.DE',  name: 'Fresenius Medical',   bucket: 'eu' },
  { symbol: 'FRE.DE',  name: 'Fresenius',           bucket: 'eu' },
  { symbol: 'HEI.DE',  name: 'HeidelbergMaterials', bucket: 'eu' },
  { symbol: 'HEN3.DE', name: 'Henkel',              bucket: 'eu' },
  { symbol: 'HNR1.DE', name: 'Hannover Rück',       bucket: 'eu' },
  { symbol: 'IFX.DE',  name: 'Infineon',            bucket: 'eu' },
  { symbol: 'LIN.DE',  name: 'Linde',               bucket: 'eu' },
  { symbol: 'MBG.DE',  name: 'Mercedes-Benz',       bucket: 'eu' },
  { symbol: 'MRK.DE',  name: 'Merck',               bucket: 'eu' },
  { symbol: 'MTX.DE',  name: 'MTU Aero Engines',    bucket: 'eu' },
  { symbol: 'MUV2.DE', name: 'Munich Re',           bucket: 'eu' },
  { symbol: 'PAH3.DE', name: 'Porsche AG',          bucket: 'eu' },
  { symbol: 'PSAN.DE', name: 'Porsche SE',          bucket: 'eu' },
  { symbol: 'QIA.DE',  name: 'Qiagen',              bucket: 'eu' },
  { symbol: 'RHM.DE',  name: 'Rheinmetall',         bucket: 'eu' },
  { symbol: 'RWE.DE',  name: 'RWE',                 bucket: 'eu' },
  { symbol: 'SAP.DE',  name: 'SAP',                 bucket: 'eu' },
  { symbol: 'SHL.DE',  name: 'Siemens Healthineers',bucket: 'eu' },
  { symbol: 'SIE.DE',  name: 'Siemens',             bucket: 'eu' },
  { symbol: 'SY1.DE',  name: 'Symrise',             bucket: 'eu' },
  { symbol: 'VNA.DE',  name: 'Vonovia',             bucket: 'eu' },
  { symbol: 'VOW3.DE', name: 'Volkswagen',          bucket: 'eu' },
  { symbol: 'WCH.DE',  name: 'Wacker Chemie',       bucket: 'eu' },
  { symbol: 'ZAL.DE',  name: 'Zalando',             bucket: 'eu' },
];

export const EUROSTOXX50_EXTRA: readonly Constituent[] = [
  // Members not already in DAX40
  { symbol: 'ABINBEd.DE', name: 'AB InBev',         bucket: 'eu' },
  { symbol: 'ASML',       name: 'ASML',             bucket: 'eu' },
  { symbol: 'BNPd.DE',    name: 'BNP Paribas',      bucket: 'eu' },
  { symbol: 'CRHd.DE',    name: 'CRH',              bucket: 'eu' },
  { symbol: 'ELFD.DE',    name: 'EssilorLuxottica', bucket: 'eu' },
  { symbol: 'ENGId.DE',   name: 'Engie',            bucket: 'eu' },
  { symbol: 'ERICD.DE',   name: 'Ericsson',         bucket: 'eu' },
  { symbol: 'FP.PA',      name: 'TotalEnergies',    bucket: 'eu' },
  { symbol: 'IBE.MC',     name: 'Iberdrola',        bucket: 'eu' },
  { symbol: 'INGA.AS',    name: 'ING Group',        bucket: 'eu' },
  { symbol: 'ISDX',       name: 'Inditex (Zara)',   bucket: 'eu' },
  { symbol: 'MC.PA',      name: 'LVMH',             bucket: 'eu' },
  { symbol: 'MUNGd.DE',   name: 'Munich Re',        bucket: 'eu' },
  { symbol: 'NN.AS',      name: 'NN Group',         bucket: 'eu' },
  { symbol: 'NVO',        name: 'Novo Nordisk',     bucket: 'eu' },
  { symbol: 'OR.PA',      name: "L'Oréal",          bucket: 'eu' },
  { symbol: 'PHG.AS',     name: 'Philips',          bucket: 'eu' },
  { symbol: 'SAN.PA',     name: 'Sanofi',           bucket: 'eu' },
  { symbol: 'SAN.MC',     name: 'Banco Santander',  bucket: 'eu' },
  { symbol: 'SGO.PA',     name: 'Saint-Gobain',     bucket: 'eu' },
  { symbol: 'STMd.DE',    name: 'STMicroelectronics',bucket: 'eu' },
  { symbol: 'SU.PA',      name: 'Schneider Electric',bucket: 'eu' },
  { symbol: 'TTE.PA',     name: 'TotalEnergies',    bucket: 'eu' },
  { symbol: 'VOLVB.ST',   name: 'Volvo',            bucket: 'eu' },
];

export const NASDAQ100: readonly Constituent[] = [
  { symbol: 'AAPL',  name: 'Apple',             bucket: 'us' },
  { symbol: 'MSFT',  name: 'Microsoft',         bucket: 'us' },
  { symbol: 'NVDA',  name: 'Nvidia',            bucket: 'us' },
  { symbol: 'AMZN',  name: 'Amazon',            bucket: 'us' },
  { symbol: 'META',  name: 'Meta',              bucket: 'us' },
  { symbol: 'GOOGL', name: 'Alphabet A',        bucket: 'us' },
  { symbol: 'GOOG',  name: 'Alphabet C',        bucket: 'us' },
  { symbol: 'TSLA',  name: 'Tesla',             bucket: 'us' },
  { symbol: 'AVGO',  name: 'Broadcom',          bucket: 'us' },
  { symbol: 'COST',  name: 'Costco',            bucket: 'us' },
  { symbol: 'NFLX',  name: 'Netflix',           bucket: 'us' },
  { symbol: 'AMD',   name: 'AMD',               bucket: 'us' },
  { symbol: 'QCOM',  name: 'Qualcomm',          bucket: 'us' },
  { symbol: 'AMAT',  name: 'Applied Materials', bucket: 'us' },
  { symbol: 'INTU',  name: 'Intuit',            bucket: 'us' },
  { symbol: 'TXN',   name: 'Texas Instruments', bucket: 'us' },
  { symbol: 'BKNG',  name: 'Booking Holdings',  bucket: 'us' },
  { symbol: 'AMGN',  name: 'Amgen',             bucket: 'us' },
  { symbol: 'ISRG',  name: 'Intuitive Surgical',bucket: 'us' },
  { symbol: 'MU',    name: 'Micron Technology', bucket: 'us' },
  { symbol: 'LRCX',  name: 'Lam Research',      bucket: 'us' },
  { symbol: 'PANW',  name: 'Palo Alto Networks',bucket: 'us' },
  { symbol: 'KLAC',  name: 'KLA Corp',          bucket: 'us' },
  { symbol: 'ADI',   name: 'Analog Devices',    bucket: 'us' },
  { symbol: 'SNPS',  name: 'Synopsys',          bucket: 'us' },
  { symbol: 'CDNS',  name: 'Cadence Design',    bucket: 'us' },
  { symbol: 'MRVL',  name: 'Marvell Tech',      bucket: 'us' },
  { symbol: 'ADP',   name: 'ADP',               bucket: 'us' },
  { symbol: 'ORCL',  name: 'Oracle',            bucket: 'us' },
  { symbol: 'PYPL',  name: 'PayPal',            bucket: 'us' },
  { symbol: 'MAR',   name: 'Marriott',          bucket: 'us' },
  { symbol: 'MDLZ',  name: 'Mondelez',          bucket: 'us' },
  { symbol: 'ABNB',  name: 'Airbnb',            bucket: 'us' },
  { symbol: 'REGN',  name: 'Regeneron',         bucket: 'us' },
  { symbol: 'GILD',  name: 'Gilead Sciences',   bucket: 'us' },
  { symbol: 'VRTX',  name: 'Vertex Pharma',     bucket: 'us' },
  { symbol: 'CEG',   name: 'Constellation Energy',bucket: 'us' },
  { symbol: 'CTAS',  name: 'Cintas',            bucket: 'us' },
  { symbol: 'FANG',  name: 'Diamondback Energy',bucket: 'us' },
  { symbol: 'MNST',  name: 'Monster Beverage',  bucket: 'us' },
  { symbol: 'CSX',   name: 'CSX Corp',          bucket: 'us' },
  { symbol: 'PAYX',  name: 'Paychex',           bucket: 'us' },
  { symbol: 'FTNT',  name: 'Fortinet',          bucket: 'us' },
  { symbol: 'FAST',  name: 'Fastenal',          bucket: 'us' },
  { symbol: 'ODFL',  name: 'Old Dominion',      bucket: 'us' },
  { symbol: 'APP',   name: 'Applovin',          bucket: 'us' },
  { symbol: 'CRWD',  name: 'CrowdStrike',       bucket: 'us' },
  { symbol: 'DXCM',  name: 'Dexcom',            bucket: 'us' },
  { symbol: 'IDXX',  name: 'IDEXX Labs',        bucket: 'us' },
  { symbol: 'ILMN',  name: 'Illumina',          bucket: 'us' },
  { symbol: 'KDP',   name: 'Keurig Dr Pepper',  bucket: 'us' },
  { symbol: 'MCHP',  name: 'Microchip Tech',    bucket: 'us' },
  { symbol: 'MRNA',  name: 'Moderna',           bucket: 'us' },
  { symbol: 'ON',    name: 'ON Semiconductor',  bucket: 'us' },
  { symbol: 'PCAR',  name: 'PACCAR',            bucket: 'us' },
  { symbol: 'PDD',   name: 'PDD Holdings',      bucket: 'us' },
  { symbol: 'ROST',  name: 'Ross Stores',       bucket: 'us' },
  { symbol: 'SBUX',  name: 'Starbucks',         bucket: 'us' },
  { symbol: 'TTD',   name: 'The Trade Desk',    bucket: 'us' },
  { symbol: 'VRSK',  name: 'Verisk Analytics',  bucket: 'us' },
  { symbol: 'XEL',   name: 'Xcel Energy',       bucket: 'us' },
  { symbol: 'ZS',    name: 'Zscaler',           bucket: 'us' },
  { symbol: 'ADBE',  name: 'Adobe',             bucket: 'us' },
  { symbol: 'ADSK',  name: 'Autodesk',          bucket: 'us' },
  { symbol: 'AEP',   name: 'American Electric', bucket: 'us' },
  { symbol: 'BIIB',  name: 'Biogen',            bucket: 'us' },
  { symbol: 'BKR',   name: 'Baker Hughes',      bucket: 'us' },
  { symbol: 'CDW',   name: 'CDW Corp',          bucket: 'us' },
  { symbol: 'CHTR',  name: 'Charter Comm',      bucket: 'us' },
  { symbol: 'CMCSA', name: 'Comcast',           bucket: 'us' },
  { symbol: 'CPRT',  name: 'Copart',            bucket: 'us' },
  { symbol: 'DLTR',  name: 'Dollar Tree',       bucket: 'us' },
  { symbol: 'EA',    name: 'Electronic Arts',   bucket: 'us' },
  { symbol: 'EXC',   name: 'Exelon',            bucket: 'us' },
  { symbol: 'GFS',   name: 'GlobalFoundries',   bucket: 'us' },
  { symbol: 'HON',   name: 'Honeywell',         bucket: 'us' },
  { symbol: 'INTC',  name: 'Intel',             bucket: 'us' },
  { symbol: 'KHC',   name: 'Kraft Heinz',       bucket: 'us' },
  { symbol: 'LULU',  name: 'Lululemon',         bucket: 'us' },
  { symbol: 'MELI',  name: 'MercadoLibre',      bucket: 'us' },
  { symbol: 'NXPI',  name: 'NXP Semiconductors',bucket: 'us' },
  { symbol: 'TEAM',  name: 'Atlassian',         bucket: 'us' },
  { symbol: 'TMUS',  name: 'T-Mobile US',       bucket: 'us' },
  { symbol: 'TSCO',  name: 'Tractor Supply',    bucket: 'us' },
  { symbol: 'WBA',   name: 'Walgreens',         bucket: 'us' },
  { symbol: 'WDAY',  name: 'Workday',           bucket: 'us' },
  { symbol: 'WDC',   name: 'Western Digital',   bucket: 'us' },
  { symbol: 'GEHC',  name: 'GE HealthCare',     bucket: 'us' },
  { symbol: 'GFS',   name: 'GlobalFoundries',   bucket: 'us' },
  { symbol: 'LIN',   name: 'Linde',             bucket: 'us' },
];

export const CRYPTO_TOP20: readonly Constituent[] = [
  { symbol: 'BTC',   name: 'Bitcoin',          bucket: 'crypto' },
  { symbol: 'ETH',   name: 'Ethereum',         bucket: 'crypto' },
  { symbol: 'BNB',   name: 'BNB',              bucket: 'crypto' },
  { symbol: 'SOL',   name: 'Solana',           bucket: 'crypto' },
  { symbol: 'XRP',   name: 'XRP',              bucket: 'crypto' },
  { symbol: 'DOGE',  name: 'Dogecoin',         bucket: 'crypto' },
  { symbol: 'ADA',   name: 'Cardano',          bucket: 'crypto' },
  { symbol: 'AVAX',  name: 'Avalanche',        bucket: 'crypto' },
  { symbol: 'LINK',  name: 'Chainlink',        bucket: 'crypto' },
  { symbol: 'DOT',   name: 'Polkadot',         bucket: 'crypto' },
  { symbol: 'MATIC', name: 'Polygon',          bucket: 'crypto' },
  { symbol: 'UNI',   name: 'Uniswap',          bucket: 'crypto' },
  { symbol: 'AAVE',  name: 'Aave',             bucket: 'crypto' },
  { symbol: 'ATOM',  name: 'Cosmos',           bucket: 'crypto' },
  { symbol: 'LTC',   name: 'Litecoin',         bucket: 'crypto' },
  { symbol: 'NEAR',  name: 'NEAR Protocol',    bucket: 'crypto' },
  { symbol: 'OP',    name: 'Optimism',         bucket: 'crypto' },
  { symbol: 'ARB',   name: 'Arbitrum',         bucket: 'crypto' },
  { symbol: 'SUI',   name: 'Sui',              bucket: 'crypto' },
  { symbol: 'TON',   name: 'Toncoin',          bucket: 'crypto' },
];

function buildFullUniverse(): Constituent[] {
  const seen = new Set<string>();
  const result: Constituent[] = [];
  for (const c of [...DAX40, ...EUROSTOXX50_EXTRA, ...NASDAQ100, ...CRYPTO_TOP20]) {
    if (!seen.has(c.symbol)) {
      seen.add(c.symbol);
      result.push(c);
    }
  }
  return result;
}

export const FULL_UNIVERSE: readonly Constituent[] = buildFullUniverse();

// Helpers for existing lib/universe.ts and analysis logic
export const CRYPTO_SYMBOLS = CRYPTO_TOP20.map(c => c.symbol);
export const EU_SYMBOLS     = [...DAX40, ...EUROSTOXX50_EXTRA].filter((v, i, a) => a.findIndex(x => x.symbol === v.symbol) === i).map(c => c.symbol);
export const US_SYMBOLS     = NASDAQ100.filter((v, i, a) => a.findIndex(x => x.symbol === v.symbol) === i).map(c => c.symbol);
